language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: K73ylChK9cbfeX4m1uXu5yRcNzBglvssjjNw6U9bSjS/NXmOtuVT1lyXw+BGRR5LHIN3Pt1YT1GPNZC4MOuvxmZnvIXQOXbXHqgcnH5E+CHxM2udd8ho0ozOoEG56ly4U467rqZlrzLPxkzWyfmGJNgP4WOOKeKGf15HlKaNO/dmPiZWkBY6d/D4DTaaWzoFoFy7YaAqJ8vGRrvQV6gVQV5AXdUIlEsCIWoVaEO3QfTTVC8/yskhw4Z+V77NCsjzAxDF00yKg/cRxFhNUK4UAbQHZ/7x8rZliU9+eyLuYI+9FqgO6irLwUD6KhmDd5Sa9TxY7mSYLlWzoikRRLDfVFn9lbCB7XeX4xZVgF//kp2nCGISrlg7cr5ZwTYYeuwub/p2LMNZVxUsU46OSCaLWpbQS4oOH3uWXe7ZruJvJasfpJPui+IhwVZ3u4rTe2GyRg4QeEa4wzVDld32HRSib4nO2i6ZfcY3rNMOVTT2rx7nNS9nwMCVXF9hZqVnX05/wRQyd0KfW5C2ka9AL6YtoXW11+03LYifqpJ/BpJJybQR3Bwhp/OrKomK6gM3Swf4JM5NysCgMnqCoSinCW53wkMNbH4lh25Fsv0xArxEB3jCgc1PDhoOodADQkJ0KC3LFlE1Z2D+is2WqKbJ0LhqpTkPFIqkNjxdVrv+0SNwNyA=
  email: false
